### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by sdrshnptl** [mikelduke/ESP8266WifiDisplay#1]
Hi Mike!
You made a very good git project, i appreciate that.
Can you please explain how following function will be work?
# define URL "http:// YOUR URL / ESP8266LCD.php"

Where I supposed to host/store .php file  and how i insert that link in "YOUR URL"
Thanks!

**Comment by mikelduke** [comment]
You can install something like apache and php on any linux system to host the php script, or write something similar in almost any other language.
